steps:
  - command: |
      set -euo pipefail
      ../script/generate-release-train.py \
          --chart deleteme-vibhu \
          --repo-name deleteme-test-vibhu \
          --prune false \
          --skip-deployment-to-production true \
          --release-train-disabled true \
        | buildkite-agent pipeline upload
    label: ":pipeline: $CHART"
    agents:
      queue: "charts-in-cluster"
      is_not_cornwall: "true"
      ready: "true"
      cluster: "global"
      environment: "production"
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2
        - exit_status: 255 # Forced agent shutdown
          limit: 2
        - exit_status: 1 # Application errors
          limit: 2
